################################### Default Configuration ############################
baseurl = "https://monkiprojects.com/"
title = "Monki Projects"
theme = "chimp-hugo"
# post excert
summarylength = "20"

# unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Multilingual Mode ##########################################

defaultContentLanguage = "en"
disableLanguages = []


#################################### Plugins ##########################################

# CSS Plugins
# [[params.plugins.css]]
# link = "plugins/"

# JS Plugins
[[params.plugins.js]]
link = "https://kit.fontawesome.com/904a334a59.js"


###################################### Navigation ######################################

# homepage section menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Apps"
url = "/apps"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3

[[menu.main]]
name = "Team"
url = "/team"
weight = 3

#[[menu.main]]
#name = "Reviews"
#url = "/#testimonials"
#weight = 4

# Footer menu
[[menu.footer]]
identifier = "apps"
name = "Apps"
url = "/apps"
weight = 1

[[menu.footer]]
name = "Monki Map"
url = "/apps/monki-map"
parent = "apps"
weight = 1

[[menu.footer]]
identifier = "support"
name = "Support"
weight = 2

[[menu.footer]]
name = "Documentation"
url = "https://docs.monkiprojects.com"
parent = "support"
weight = 1

[[menu.footer]]
name = "FAQ"
parent = "support"
weight = 2
[menu.footer.params]
  class = "disabled"

[[menu.footer]]
name = "Guides"
parent = "support"
weight = 3
[menu.footer.params]
  class = "disabled"

[[menu.footer]]
name = "System status"
parent = "support"
weight = 99
[menu.footer.params]
  class = "disabled"

[[menu.footer]]
name = "Pricing"
parent = "support"
weight = 4
[menu.footer.params]
  class = "disabled"

[[menu.footer]]
identifier = "company"
name = "Monki Projects"
weight = 3

[[menu.footer]]
name = "About"
parent = "company"
weight = 1
[menu.footer.params]
  class = "disabled"

[[menu.footer]]
name = "Blog"
url = "/blog"
parent = "company"
weight = 2

[[menu.footer]]
name = "Team"
url = "/team"
parent = "company"
weight = 3

[[menu.footer]]
name = "Contact"
url = "/contact"
parent = "company"
weight = 49

[[menu.footer]]
name = "Media resources"
parent = "company"
weight = 50
[menu.footer.params]
  class = "disabled"

# [[menu.footer]]
# name = "Tags"
# url = "/tags"
# weight = 50

[[menu.footer]]
identifier = "legal"
name = "Legal"
weight = 99

[[menu.footer]]
name = "Terms & Conditions"
# url = "/terms-conditions"
parent = "legal"
weight = 1
[menu.footer.params]
  class = "disabled"

[[menu.footer]]
name = "Privacy Policy"
# url = "/privacy-policy"
parent = "legal"
weight = 2
[menu.footer.params]
  class = "disabled"


########################### Default parameters ##########################
[params]
logo_width = "256px"
# Meta data
description = "Making apps and tools for the parkour — an urban sport — community."
author = "Monki Projects"
# contact form action
#contact_form_action = "#" # contact form works with https://formspree.io

# Icon – Icon Only
[params.logo.icon_only.normal]
on_light = "https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Dark-On-Light"
on_dark = "https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Light-On-Dark"
[params.logo.icon_only.colored]
on_light = "https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Colored-On-Light"
on_dark = "https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Colored-On-Dark"

# Icon – Vertical
[params.logo.vertical.normal]
on_light = "https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Vertical-Dark-On-Light"
on_dark = "https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Vertical-Light-On-Dark"
[params.logo.vertical.colored]
on_light = "https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Vertical-Colored-On-Light"
on_dark = "https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Vertical-Colored-On-Dark"

# Icon – Horizontal
[params.logo.horizontal.normal]
on_light = "https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Horizontal-Dark-On-Light"
on_dark = "https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Horizontal-Light-On-Dark"
[params.logo.horizontal.colored]
on_light = "https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Horizontal-Colored-On-Light"
on_dark = "https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Horizontal-Colored-On-Dark"


################################### English language #####################################
[languages.en]
languageName = "En 🇺🇸"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

# Language overrides
copyright = """
Made with ❤️ in France & Proudly hosted on [Clever Cloud](https://clever-cloud.com)

Copyright &copy; 2020-2021 Monki Projects.
"""


################################### French language #####################################
[languages.fr]
languageName = "Fr 🇫🇷"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2

# Language overrides
title = "Monki Projects"
copyright = """
Fait avec ❤️ en France & Fièrement hébergé chez [Clever Cloud](https://clever-cloud.com).

Copyright &copy; 2020-2021 Monki Projects.
"""

[languages.fr.params]
description = "Des applications et des outils pour la communauté du parkour – un sport urbain."

[languages.fr.params.navigation]
help = "Aide"

# homepage section menu
[[languages.fr.menu.main]]
name = "Accueil"
url = "/"
weight = 1

[[languages.fr.menu.main]]
name = "Apps"
url = "/apps"
weight = 2

[[languages.fr.menu.main]]
name = "Blog"
url = "/blog"
weight = 3

[[languages.fr.menu.main]]
name = "Équipe"
url = "/equipe"
weight = 4

#[[languages.fr.menu.main]]
#name = "Témoignages"
#url = "/#temoignages"
#weight = 5

# Footer menu
[[languages.fr.menu.footer]]
identifier = "apps"
name = "Apps"
url = "/apps"
weight = 1

[[languages.fr.menu.footer]]
name = "Monki Map"
url = "/apps/monki-map"
parent = "apps"
weight = 1

[[languages.fr.menu.footer]]
identifier = "support"
name = "Support"
weight = 2

[[languages.fr.menu.footer]]
name = "Documentation"
url = "https://docs.monkiprojects.com"
parent = "support"
weight = 1

[[languages.fr.menu.footer]]
name = "FAQ"
parent = "support"
weight = 2
[languages.fr.menu.footer.params]
  class = "disabled"

[[languages.fr.menu.footer]]
name = "Guides"
parent = "support"
weight = 3
[languages.fr.menu.footer.params]
  class = "disabled"

[[languages.fr.menu.footer]]
name = "État des systèmes"
parent = "support"
weight = 99
[languages.fr.menu.footer.params]
  class = "disabled"

[[languages.fr.menu.footer]]
name = "Tarification"
parent = "support"
weight = 4
[languages.fr.menu.footer.params]
  class = "disabled"

[[languages.fr.menu.footer]]
identifier = "entreprise"
name = "Monki Projects"
weight = 3

[[languages.fr.menu.footer]]
name = "À propos"
parent = "entreprise"
weight = 1
[languages.fr.menu.footer.params]
  class = "disabled"

[[languages.fr.menu.footer]]
name = "Blog"
url = "/blog"
parent = "entreprise"
weight = 2

[[languages.fr.menu.footer]]
name = "Équipe"
url = "/equipe"
parent = "entreprise"
weight = 3

[[languages.fr.menu.footer]]
name = "Contact"
url = "/contact"
parent = "entreprise"
weight = 49

[[languages.fr.menu.footer]]
name = "Ressources médiatiques"
parent = "entreprise"
weight = 50
[languages.fr.menu.footer.params]
  class = "disabled"

# [[languages.fr.menu.footer]]
# name = "Tags"
# url = "/tags"
# weight = 50

[[languages.fr.menu.footer]]
identifier = "legal"
name = "Légal"
weight = 99

[[languages.fr.menu.footer]]
name = "Termes & conditions"
# url = "/termes-conditions"
parent = "legal"
weight = 1
[languages.fr.menu.footer.params]
  class = "disabled"

[[languages.fr.menu.footer]]
name = "Politique de confidentialité"
# url = "/confidentialite"
parent = "legal"
weight = 2
[languages.fr.menu.footer.params]
  class = "disabled"
