############################## Default Configuration ############################
baseurl: https://monkiprojects.com/
title: Monki Projects
theme: chimp-hugo
# Post excert
summarylength: 20

# Unsafe HTML
markup:
  goldmark:
    renderer:
      unsafe: true


############### Multilingual Mode ###############
defaultContentLanguage: en


############################## Default Parameters ############################
params:
  ########## Hugo Parameters ##########
  author: Monki Projects

  ########## Favicon ##########
  favicon_html: |
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/site.webmanifest">
    <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#fb923c">
    <link rel="shortcut icon" href="/favicon/favicon.ico">
    <meta name="msapplication-TileColor" content="#fb923c">
    <meta name="msapplication-config" content="/favicon/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">

  ########## Plugins ##########
  plugins:
    ##### CSS Plugins #####
    css:
      # - link: plugins/lorem/ipsum.css
    ##### JS Plugins #####
    js:
      - link: https://kit.fontawesome.com/904a334a59.js

  ########## Brand Icon ##########
  logo:
    ##### Icon – Icon Only #####
    icon_only:
      normal:
        on_light: https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Dark-On-Light
        on_dark: https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Light-On-Dark
      colored:
        on_light: https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Colored-On-Light
        on_dark: https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Colored-On-Dark
    ##### Icon – Vertical #####
    vertical:
      normal:
        on_light: https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Vertical-Dark-On-Light
        on_dark: https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Vertical-Light-On-Dark
      colored:
        on_light: https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Vertical-Colored-On-Light
        on_dark: https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Vertical-Colored-On-Dark
    ##### Icon – Horizontal #####
    horizontal:
      normal:
        on_light: https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Horizontal-Dark-On-Light
        on_dark: https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Horizontal-Light-On-Dark
      colored:
        on_light: https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Horizontal-Colored-On-Light
        on_dark: https://res.cloudinary.com/monki-projects/image/upload/f_auto,w_auto/v1618051692/logo/monki-projects/Monki-Projects-Logo-Horizontal-Colored-On-Dark
