################################### Global Configuration ############################
# See https://gohugo.io/getting-started/configuration/#all-configuration-settings

baseurl = "https://monkiprojects.com/"
title = "Home | Monki Projects"
theme = "vex-hugo"
# post excert
summarylength = "20"

# Update git commit dates
enableGitInfo = true


#################################### Multilingual Mode ##########################################

defaultContentLanguage = "en"
disableLanguages = []


#################################### Markup Configuration ##########################################

# unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://kit.fontawesome.com/904a334a59.js"


###################################### Navigation ######################################

# homepage section menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Apps"
url = "apps"
weight = 2

[[menu.main]]
name = "Blog"
url = "blog"
weight = 3

[[menu.main]]
name = "Team"
url = "team"
weight = 3

#[[menu.main]]
#name = "Reviews"
#pre = "#"
#url = "testimonial"
#weight = 4

# footer menu
[[menu.footer]]
name = "Apps"
url = "apps"
weight = 1

[[menu.footer]]
name = "Blog"
url = "blog"
weight = 2

[[menu.footer]]
name = "Team"
url = "team"
weight = 3

[[menu.footer]]
name = "Contact"
url = "contact"
weight = 4

[[menu.footer]]
name = "Terms & Conditions"
url = "terms-conditions"
weight = 99

[[menu.footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 100


########################### Default parameters ##########################
[params]
logo = "images/icon/Logo-Horizontal.png"
logo_width = "256px"
# Meta data
description = "Making apps and tools for the parkour — an urban sport — community."
author = "Monki Projects"
# contact form action
#contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

[params.navigation]
help = "Help"


################################### English language #####################################
[languages.en]
languageName = "En 🇺🇸"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

# Language overrides
copyright = """
Made with ❤️ in France & Proudly hosted on [Clever Cloud](https://clever-cloud.com)

Copyright &copy; 2020 Monki Projects. Original theme by [Themefisher](https://themefisher.com/).
"""


################################### French language #####################################
[languages.fr]
languageName = "Fr 🇫🇷"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2

# Language overrides
title = "Accueil | Monki Projects"
copyright = """
Fait avec ❤️ en France & Fièrement hébergé chez [Clever Cloud](https://clever-cloud.com).

Copyright &copy; 2020 Monki Projects. Thème original par [Themefisher](https://themefisher.com/).
"""

[languages.fr.params]
description = "Des applications et des outils pour la communauté du parkour – un sport urbain."

[languages.fr.params.navigation]
help = "Aide"

# homepage section menu
[[languages.fr.menu.main]]
name = "Accueil"
url = "/"
weight = 1

[[languages.fr.menu.main]]
name = "Apps"
url = "apps"
weight = 2

[[languages.fr.menu.main]]
name = "Blog"
url = "blog"
weight = 3

[[languages.fr.menu.main]]
name = "Équipe"
url = "equipe"
weight = 4

#[[languages.fr.menu.main]]
#name = "Témoignages"
#pre = "#"
#url = "testimonial"
#weight = 5

# footer menu
[[languages.fr.menu.footer]]
name = "Apps"
url = "apps"
weight = 1

[[languages.fr.menu.footer]]
name = "Blog"
url = "blog"
weight = 2

[[languages.fr.menu.footer]]
name = "Équipe"
url = "equipe"
weight = 3

[[languages.fr.menu.footer]]
name = "Contact"
url = "contact"
weight = 4

[[languages.fr.menu.footer]]
name = "Termes & Conditions"
url = "terms-conditions"
weight = 99

[[languages.fr.menu.footer]]
name = "Politique de Confidentialité"
url = "privacy-policy"
weight = 100
