---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: heading
  label: "\U0001F1EC\U0001F1E7 English"
- type: directory
  path: content/english/blog
  label: Blog
  create: documents
  match: "*"
  exclude: _index.md
- type: heading
  label: "\U0001F1EB\U0001F1F7 Français"
- type: directory
  path: content/french/blog
  label: Blog
  create: documents
  match: "*"
  exclude: _index.md
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.79.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.79.0
